from llama_index.core.prompts.base import PromptTemplate
from llama_index.core.prompts.prompt_type import PromptType

############################################
# zero shot Prompt
############################################

yes_no_qa_prompt = PromptTemplate(
        "You are a helpful assistant that answers questions given Context information and not prior knowledge.\n"
        "Answers can be yes or no. You have to write yes or no and nothing else. Do not write it depends or anything similar.\n" 
        "You HAVE to write only yes or no, even if you are uncertain.\n"
        "---------------------\n"
        "Context information: {context_str}\n"
        "---------------------\n"
        "Question : {query_str}\n"
        "Output Format: Answer: __yes/no__ \n"
    )

span_qa_prompt = PromptTemplate(
        "You are a helpful assistant that answers questions given Context information and not prior knowledge.\n"
        "Answers must be a short span of the Context information. Do not write it depends or anything similar.\n" 
        "You have to extract the span from the Context information. Do not write anything else.\n"
        "---------------------\n"
        "Context information: {context_str}\n"
        "---------------------\n"
        "Question : {query_str}\n"
        "Output Format: Answer: __answer__ \n"
    )
    
yes_no_con_qa_prompt = PromptTemplate(
        "You are a helpful assistant that answers questions given Context information and not prior knowledge.\n"
        "Answers can be yes or no. You have to write yes or no and nothing else. Do not write it depends or anything similar.\n" 
        "You HAVE to write only yes or no, even if you are uncertain.\n"
        "Some answers may required the assumption of some sentences from the text to be true. If you think that is the case, you must write the full sentence(s) that you think are required to be true after the answer. We call these sentence(s) 'conditions'. You must have used this sentence(s) in your reasoning steps.\n"
        "---------------------\n"
        "Context information: {context_str}\n"
        "---------------------\n"
        "Question : {query_str}\n"
        "Output Format: Answer: __yes/no__ , Conditions: __condition__ \n"
    )

span_con_qa_prompt = PromptTemplate(
        "You are a helpful assistant that answers questions given Context information and not prior knowledge.\n"
        "Answers must be a short span extracted from the Context information. Do not write it depends or anything similar.\n" 
        "You have to only extract the span of text from the Context information. Do not write anything else.\n"
        "Some answers may required the assumption of some sentences from the text to be true. If you think that is the case, you must write the full sentence(s) that you think are required to be true after the answer. We call these sentence(s) 'conditions'. You must have used this sentence(s) in your reasoning steps.\n"
        "---------------------\n"
        "Context information: {context_str}\n"
        "---------------------\n"
        "Question : {query_str}\n"
        "Output Format: Answer: __answer__ , Conditions: __condition__ \n"
    )

############################################
# static few_shot Prompt   4 examples   
############################################

yes_no_qa_s4_prompt = PromptTemplate(
        "You are a helpful assistant that answers questions given Context information and not prior knowledge.\n"
        "Answers can be yes or no. You have to write yes or no and nothing else. Do not write it depends or anything similar.\n" 
        "You HAVE to write only yes or no, even if you are uncertain.\n"
        "Some examples are given below.\n"
        "---------------------\n"
        "Question: I served with the Royal Engineers during the war in Afghanistan from 2012-13, and now believe I have recently begun to experience traumatic flashbacks. . Can I claim for Post-Traumatic Stress, given the lateness of the onset of this?\n"
        "Answer: yes\n"
        "Question: My civil partner went missing just over 7 years ago. We are both British but he disappeared in Canada where we were living at the time; I came home to live in Wales 18 months ago. . Can I make a claim for a declaration of presumed death even though the missing person went missing abroad and was not living in England or Wales at the time?\n"
        "Answer: yes\n"
        "Question: My aunt has appointed me as her next of kin to oversee her finances after suffering from stroke. I want to apply as her tax relief appointee to act on her behalf. . Will I be automatically authorised to undertake this role and help her claim tax relief?\n"
        "Answer: no\n"
        "Question: My grandfather has appointed me as his financial affair attorney and i have been running his businesses efficiently . He has been diagnosed with a terminal illness and has few day to live. . Will a power of attorney still be valid after my grandfather dies?\n"
        "Answer: no\n"
        "---------------------\n"
        "Context information: {context_str}\n"
        "---------------------\n"
        "Question : {query_str}\n"
        "Output Format: Answer: __yes/no__ \n"
    )

span_qa_s4_prompt = PromptTemplate(
        "You are a helpful assistant that answers questions given Context information and not prior knowledge.\n"
        "Answers must be a short span of the document. Do not write it depends or anything similar.\n" 
        "You have to extract the span from the document. Do not write anything else.\n"
        "Some examples are given below.\n"
        "---------------------\n"
        "Question: I was badly injured whilst working on a construction site. I was evaluated as 80% disabled. I have no idea if or whether I will be able to return to work. . How much can I claim from this benefit?\n"
        "Answer: £146.32\n"
        "Question: My uncle has parkinsonism disease and appointed me to oversee his estate as his property deputy but during the application process i was overchaged by £100 by the office of the Guardian and i need a refund. . How long will it take for me to get the refund?\n"
        "Answer: up to 10 weeks to get a decision and a further 2 weeks to receive the refund\n"
        "Question: My child is 10 and has cerebal palsy. This means he is unable to walk. It is a struggle for me to get him around the house as his bedroom and the bathroom are upstairs. . Where can I get help to make adaptations to my home to help my child?\n"
        "Answer: your local council\n"
        "Question: I am a 16 year old living in Derby and was born male, I do not feel like I fit into any gender category. . What age can I apply for a certificate?\n"
        "Answer: 18 or over\n"
        "---------------------\n"
        "Context information: {context_str}\n"
        "---------------------\n"
        "Question : {query_str}\n"
        "Output Format: Answer: __answer__ \n"
    )
    
yes_no_con_qa_s4_prompt = PromptTemplate(
        "You are a helpful assistant that answers questions given Context information and not prior knowledge.\n"
        "Answers can be yes or no. You have to write yes or no and nothing else. Do not write it depends or anything similar.\n" 
        "You HAVE to write only yes or no, even if you are uncertain.\n"
        "Some answers may required the assumption of some sentences from the text to be true. If you think that is the case, you must write the full sentence(s) that you think are required to be true after the answer. We call these sentence(s) 'conditions'. You must have used this sentence(s) in your reasoning steps.\n"
        "Some examples are given below.\n"
        "---------------------\n"
        "Question: I live in England, and my wife and I will soon be welcoming our first adoptive child into our home. As a full time employee who has been with the same company for 4 years, I have decided to take my full 52-week entitlement of Adoption Leave and have given the required notice to my employer. . Is it possible for my wife to claim Paternity Leave (even though she is a woman)?\n"
        "Answer: yes Conditions: <p>You need to qualify to get the fuel allowance through the National Concessionary Fuel Scheme (NCFS), and you can only get the cash allowance if you’re already getting fuel through the scheme.</p>\n"
        "Question: I am 24, live in England with my partner and 5 year old son, and am currently studying for a degree at University. I get undergraduate student finance, and my partner works full time. . Can I apply for a grant to cover the cost of childcare for my son whilst I attend my course?\n"
        "Answer: yes Conditions: <li>your childcare provider is on the Ofsted Early Years Register or General Childcare Register - check with your provider</li>\n"
        "<li>neither you or your partner are claiming Tax-Free Childcare, the childcare element of working Tax Credit or Universal Credit</li>\n"
        "<li>neither you or your partner receive help with childcare costs from the National Health Service (NHS)</li>\n"
        "<li>you’re not getting a Postgraduate Loan</li>\n"
        "<li>the children in your grant application are financially dependent on you</li>\n"
        "<li>if your child is cared for at home, the carer cannot be a relative and must be registered with an appropriate body - check with Student Finance England</li>\n"
        "Question: Me and my husband have decided to adopt a child from China. The child is arriving in England in 2 weeks. I work full time and I want to sort out time off work to care for it. . Am I eligible for statutory adoption pay and how long is it paid for?\n"
        "Answer: up to 39 weeks Conditions: <li>have been continuously employed by your employer for at least 26 weeks by the week you were matched with a child</li>\n"
        "<li>earn on average at least £120 a week (before tax)</li>\n"
        "<li>give the correct notice</li>\n"
        "<li>give proof of the adoption or surrogacy</li>\n"
        "<p>The requirements are the same if you’re adopting from overseas, except you must have been continuously employed by your employer for at least 26 weeks when you start getting adoption pay.</p>\n"
        "<p>You must also sign form SC6 if you’re adopting from overseas with a partner. This confirms you’re not taking paternity leave or pay.</p>\n"
        "Question: We are blessed with triplet baby boys. I am so happy about it. I am planning take paternity leave to take care of the boys . Can I take paid paternity leave and how many weeks of paternity leave can I take off in one go?\n"
        "Answer: 1 or 2 weeks Conditions: <li>be an employee</li>\n"
        "<li>give the correct notice</li>\n"
        "<li>have been continuously employed by your employer for at least 26 weeks up to any day in the ‘qualifying week’</li>\n"
        "---------------------\n"
        "Context information: {context_str}\n"
        "---------------------\n"
        "Question : {query_str}\n"
        "Output Format: Answer: __yes/no__ , Conditions: __condition__ \n"
    )

span_con_qa_s4_prompt = PromptTemplate(
        "You are a helpful assistant that answers questions given Context information and not prior knowledge.\n"
        "Answers must be a short span extracted from the Context information. Do not write it depends or anything similar.\n" 
        "You have to only extract the span of text from the Context information. Do not write anything else.\n"
        "Some answers may required the assumption of some sentences from the text to be true. If you think that is the case, you must write the full sentence(s) that you think are required to be true after the answer. We call these sentence(s) 'conditions'. You must have used this sentence(s) in your reasoning steps.\n"
        "Some examples are given below.\n"
        "---------------------\n"
        "Question: I have written a will with a help of a solicitor before six years and I have lot of changes in my assets and I am planning to make some changes to my will . Can I make changes to my will once I have signed ? what is the process to amend a will ?\n"
        "Answer: make a new will Conditions: <p>For major changes you should make a new will.</p>\n"
        "Question: I work as a healthcare assistant  and i have tested positive for corona virus and i am in isolation with severe covid symptoms. I can’t go to work due to this effect and i want to seek income support from my employer. . Can i get help and how much will my employer pay me?\n"
        "Answer: £96.35 a week Conditions: <p>To qualify for Statutory Sick Pay (SSP) you must:</p>\n"
        "<li>be classed as an employee and have done some work for your employer</li>\n"
        "<li>earn an average of at least £120 per week</li>\n"
        "Question: My brother and his wife tragically died in a car accident last year. I agreed to become the guardians of their children. . How much guardian's allowance can I claim?\n"
        "Answer: £18 a week per child Conditions: <li>you qualify for Child Benefit</li>\n"
        "<li>one of the parents was born in the UK (or was living in the UK since the age of 16 for at least 52 weeks in any 2-year period)</li>\n"
        "Question: I am a UK taxpayer and I believe my income tax has been miscalculated by HMRC. They have sent me a letter telling me I owe them £5000. I want to appeal this decision. . When will I receive the tribunal decision?\n"
        "Answer: within 1 month Conditions: <li>in writing within 1 month, if you’ve had a ‘basic’ case - you’ll sometimes get a decision on the day</li>\n"
        "---------------------\n"
        "Context information: {context_str}\n"
        "---------------------\n"
        "Question : {query_str}\n"
        "Output Format: Answer: __answer__ , Conditions: __condition__ \n"
    )
############################################
# static few_shot Prompt  with KG 4 examples   
############################################

yes_no_qa_kg_s4_prompt = PromptTemplate(
    "You are a helpful assistant that answers questions given Context information and not prior knowledge.\n"
    "Answers can be yes or no. You have to write yes or no and nothing else. Do not write it depends or anything similar.\n"
    "The context include knowledge triples in the format (subject, predicate, object). Use these triples as part of the Context information to help identify relevant information for answering the question.\n" 
    "You HAVE to write only yes or no, even if you are uncertain.\n"
    "Some examples are given below.\n"
    "---------------------\n"
    # "Context information: \n"
    # "Knowledge Triples: (finance plan, available for, Green Deal assessment improvements) \n (loan, available for, insulation replacement) \n "
    "Question: I own a home and energy bills are always high. When I hired a engineer to assess why my energy bills are high. He mentioned the problem is because of insulation. I can't afford to replace the insulation. These energy improvements have been recommended in my Green Deal assessment. Can I get a loan to replace the insulation ? \n"
    "Answer: yes\n"
    "\n"
    # "Context information: "
    # "Knowledge Triples: (employer, applies to, Central Arbitration Committee) \n (trade union, derecognised if, employed less than 21 people for 13 weeks) \n"
    "Question: I am the owner of a high street retailing business which has fallen on hard times in the wake of the pandemic. At our peak we had over 150 employees, who were represented by a trade union whom we voluntarily recognised six years ago. Now our headcount has fallen below 20, and the remaining workers include a union shop steward who is being unreasonably obstructive of our attempts to turn the company around. I have had only 17 employees for the last year. Given the shrunken state of the business, is it now possible to get the union derecognised? \n"
    "Answer: yes\n"
    "\n"
    # "Context information: "
    # "Knowledge Triples: (test room, no access to, personal items) \n (mobile phones, stored in, locker or plastic box) \n"
    "Question: My friend Ann has booked  her ADI part 1 test . She has scheduled an important phone call a few minutes before the exam day . Will she be allowed to access her mobile phone during exam day? \n"
    "Answer: no\n"
    "\n"
    "Context information: "
    # "Knowledge Triples: (caregiver, receives, £67.60 a week) \n (caregiver, cares for, someone at least 35 hours a week) \n (Carer's Allowance, eligibility requires, 35 hours of care) \n (partner, receives, Disability Living Allowance at higher rate) \n"
    "Question: I live in Scotland, and currently care for my physically disabled partner for approximately 30 hrs per week. My partner receives Disability Living Allowance at the higher rate and I work part time, earning approximately £500pcm. Can I claim Carer's Allowance to help with my partner's care? \n"
    "Answer: no\n"
    "\n"
    "---------------------\n"
    "Context information: {context_str}\n"
    "---------------------\n"
    "Question : {query_str}\n"
    "Output Format: Answer: __yes/no__ \n"
)

span_qa_kg_s4_prompt = PromptTemplate(
    "You are a helpful assistant that answers questions given Context information and not prior knowledge.\n"
    "Answers must be a short span of the Context information. Do not write it depends or anything similar.\n" 
    "You have to extract the span from the Context information. Do not write anything else.\n"
    "The context may include knowledge triples in the format (subject, predicate, object). Use these triples as part of the Context information to help identify relevant information for answering the question.\n"
    "Some examples are given below.\n"
    "---------------------\n"
    # "Context information:  "
    # "Knowledge Triples: (judge, agrees, court sends certificate) \n (court, sends, certificate) \n (certificate, takes, several weeks) \n"
    "Question: Me and my wife were married but with the mutual consent we applied for divorce. We have  applied for a decree nisi and are now waiting for the result What happens to my application and how I will be communicated with? \n"
    "Answer: if the judge agrees, the court will send you and your husband or wife a certificate. this may take several weeks.\n"
    "\n"
    # "Context information: "
    # "Knowledge Triples: (apply, requires, age 18 or over) \n"
    "Question: I am a 16 year old living in Derby and was born male, I do not feel like I fit into any gender category. What age can I apply for a certificate? \n"
    "Answer: 18 or over\n"
    "\n"
    # "Context information: "
    # "Knowledge Triples: (first step, download and fill in, notice of appeal form) \n"
    "Question: I am a 21 year old single Algerian male who is claiming asylum on the grounds of persecution. I applied for some support whilst I get myself established here but just received a letter saying I've been declined. What is the first step in the appeals process? \n"
    "Answer: download and fill in a ‘notice of appeal’ form\n"
    "\n"
    # "Context information: "
    # "Knowledge Triples: (EWC, requires, at least 1,000 employees in EEA) \n (EWC, requires, 150 employees in each of at least 2 countries in EEA) \n"
    "Question: I work for a firm with several offices across Europe. I have heard of EWC but I am not sure if we qualify. Before I apply, what do we need to do to qualify? \n"
    "Answer: at least 1,000 employees in the eea\n"
    "\n"
    "---------------------\n"
    "Context information: {context_str}\n"
    "---------------------\n"
    "Question : {query_str}\n"
    "Output Format: Answer: __answer__ \n"
)

yes_no_con_qa_kg_s4_prompt = PromptTemplate(
    "You are a helpful assistant that answers questions given Context information and not prior knowledge.\n"
    "Answers can be yes or no. You have to write yes or no and nothing else. Do not write it depends or anything similar.\n" 
    "You HAVE to write only yes or no, even if you are uncertain.\n"
    "The context may include knowledge triples in the format (subject, predicate, object). Use these triples as part of the Context information to help identify relevant information for answering the question.\n"
    "Some answers may required the assumption of some sentences from the text to be true. If you think that is the case, you must write the full sentence(s) that you think are required to be true after the answer. We call these sentence(s) 'conditions'. You must have used this sentence(s) in your reasoning steps.\n"
    "Some examples are given below.\n"
    "---------------------\n"
    # "Context information: \n "
    # "Knowledge Triples: (arrange, payment plan, HMRC) \n (payment plan, requires, owe £30,000 or less) \n (payment plan, requires, no other payment plans or debts with HMRC) \n (payment plan, requires, tax returns up to date) \n (payment plan, requires, less than 60 days after payment deadline)\n"
    "Question: I am self employed as a caterer and always do my own taxes. I was informed recently that I had made a mistake on my last self assessment form and owe quite a substantial amount of money to HMRC. I cannot pay at the present time. Is there anything I can do to delay the repayments I have to make? \n"
    "Answer: arranging a payment plan with hmrc Conditions: If you owe Self Assessment tax and your bill is less than £30,000 you may be able to pay in monthly instalments.\n you owe £30,000 or less \n you do not have any other payment plans or debts with HMRC \n your tax returns are up to date \n it’s less than 60 days after the payment deadline \n"
    "\n"
    # "Context information: "
    # "Knowledge Triples: (Parents’ Learning Allowance, available for, full-time student with children) \n (claim, available for, full-time undergraduate course) \n (claim, available for, Initial Teacher Training course)"
    "Question: I have two children and I am currently due to start a degree course in social work this coming Autumn. Can I make a claim given that I will be studying and no longer working? \n"
    "Answer: yes Conditions: a full-time undergraduate course \n an Initial Teacher Training (ITT) course\n"
    "\n"
    # "Context information:  "
    # "Knowledge Triples: (passport, requires, blank page for visa) \n (applicant, from, outside the EU/Switzerland/Norway/Iceland/Liechtenstein) \n (applicant, from, EU/Switzerland/Norway/Iceland/Liechtenstein without biometric passport) \n"
    "Question: I am 26 and planning on applying for a start-up visa for my new business in the UK. I speak fluent English. I have a valid passport but all the pages are full. Can I use my current passport for my application? \n"
    "Answer: no Conditions: from outside the EU, Switzerland, Norway, Iceland or Liechtenstein \n from the EU, Switzerland, Norway, Iceland or Liechtenstein but do not have a biometric passport with a chip in it\n"
    "\n"
    # "Context information:  "
    # "Knowledge Triples: (home, must be offered to, old landlord or another social landlord) \n (sell, restricted in, national park) \n (sell, restricted in, area of outstanding natural beauty) \n (sell, restricted in, rural area for Right to Buy) \n"
    "Question: I purchased my current family home in Norwich, England from the local council 9 years ago under the right-to-buy scheme. With my children having now grown up and left home my partner and I are now looking to sell the house and retire to something a little smaller. Can I now sell my home to whomever I like on the open market? \n"
    "Answer: no Conditions: a national park \n an area of outstanding natural beauty \n an area the government says is rural for Right to Buy\n"
    "\n"
    "---------------------\n"
    "Context information: {context_str}\n"
    "---------------------\n"
    "Question : {query_str}\n"
    "Output Format: Answer: __yes/no__ , Conditions: __condition__ \n __condition__ \n ..."
)

span_con_qa_kg_s4_prompt = PromptTemplate(
    "You are a helpful assistant that answers questions given Context information and not prior knowledge.\n"
    "Answers must be a short span extracted from the Context information. Do not write it depends or anything similar.\n" 
    "You have to only extract the span of text from the Context information. Do not write anything else.\n"
    "The context may include knowledge triples in the format (subject, predicate, object). Use these triples as part of the Context information to help identify relevant information for answering the question.\n"
    "Some answers may required the assumption of some sentences from the text to be true. If you think that is the case, you must write the full sentence(s) that you think are required to be true after the answer. We call these sentence(s) 'conditions'. You must have used this sentence(s) in your reasoning steps.\n"
    "Some examples are given below.\n"
    "---------------------\n"
    # "Context information: "
    # "Knowledge Triples: (gowns and PPE, classified as, healthcare offensive waste) \n (offensive waste, defined as, non-clinical waste) \n (offensive waste, not contain, pharmaceutical or chemical substances) \n (offensive waste, may be unpleasant to, anyone who comes into contact) \n (healthcare offensive waste, includes, outer dressings and protective clothing like masks, gowns, gloves) \n (healthcare offensive waste, non-hazardous, 18-01-04 | 18-02-03) \n"
    "Question: I am a GP partner in a small, private medical practice in London. We have recently gotten through a lot of gowns and other PPE as a result of the COVID-19 pandemic, and these now need to be classified for disposal. How are potentially COVID-infected gowns and other PPE to be classified? \n"
    "Answer: healthcare offensive waste Conditions: ‘Offensive waste’ is non-clinical waste that’s non-infectious and does not contain pharmaceutical or chemical substances, but may be unpleasant to anyone who comes into contact with it. \n Healthcare offensive waste | Outer dressings and protective clothing like masks, gowns and gloves that are not contaminated with body fluids, and sterilised laboratory waste | Non-hazardous | 18-01-04 | 18-02-03'\n'"
    "\n"
    # "Context information: "
    # "Knowledge Triples: (ask for, permission to appeal to the Upper Tribunal) \n (appeal to Upper Tribunal, if, legal mistake with tribunal’s decision) \n (tribunal, got, law wrong) \n (tribunal, did not apply, correct law) \n (tribunal, did not follow, correct procedures) \n (tribunal, had no, evidence to support its decision) \n"
    "Question: I have recently had my appeal rejected and I am at a loss of what to do my family members are all in the uk and I wont be able to see them anymore. Is there anything I can do as my appeal has been rejected? \n"
    "Answer: you can ask for permission to appeal to the upper tribunal Conditions:  You can ask for permission to appeal to the Upper Tribunal (Immigration and Asylum Chamber) if you lose your case and you think there’s a legal mistake with the tribunal’s decision. \n got the law wrong \n do not apply the correct law \n do not follow the correct procedures, which affected the decision \n had no evidence to support its decision \n"
    "\n"
    # "Context information: "
    # "Knowledge Triples: (eligible for, Maternity Allowance) \n (Maternity Allowance, amount, £151.97 a week or 90% of average weekly earnings) \n (Maternity Allowance, paid if, cannot get Statutory Maternity Pay) \n (Maternity Allowance, requires, employed or self-employed for at least 26 weeks) \n (Maternity Allowance, requires, earning £30 a week or more in at least 13 weeks) \n "
    "Question: I am twenty weeks pregnant and work part time at present.  I am not currently  in receipt of any other benefits. Am I eligible for the Maternity allowance and if so how much will I get? \n"
    "Answer: £151.97 a week or 90% of your average weekly earnings Conditions: \n you’re employed, but cannot get Statutory Maternity Pay \n employed or self-employed for at least 26 weeks  \n earning (or classed as earning) £30 a week or more in at least 13 weeks - the weeks do not have to be together\n"
    "\n"
    # "Context information: "
    # "Knowledge Triples: (use, DBS Adult First) \n (DBS Adult First, available if, provide care services for adults) \n (care services, example, care home) \n"
    "Question: I want to recruit an employee urgently to work in a care home.I want to know her DBS checks  in the next 2 days. Which service can i use? \n"
    "Answer: dbs adult first Conditions: If you provide care services for adults (for example in a care home), you can use a service called DBS Adult First.\n"
    "\n"
    "---------------------\n"
    "Context information: {context_str}\n"
    "---------------------\n"
    "Question : {query_str}\n"
    "Output Format: Answer: __answer__ , Conditions: __condition__ \n __condition__ \n ..."
)


############################################
# static few_shot Prompt  with Context 4 examples   
############################################

yes_no_qa_c_s4_prompt = PromptTemplate(
    "You are a helpful assistant that answers questions given Context information and not prior knowledge.\n"
    "Answers can be yes or no. You have to write yes or no and nothing else. Do not write it depends or anything similar.\n"
    "You HAVE to write only yes or no, even if you are uncertain.\n"
    "Some examples are given below.\n"
    "---------------------\n"
    "Context information: You can only get a finance plan for improvements recommended in your Green Deal assessment.\n"
    "Question: I own a home and energy bills are always high. When I hired a engineer to assess why my energy bills are high. He mentioned the problem is because of insulation. I can't afford to replace the insulation. These energy improvements have been recommended in my Green Deal assessment. Can I get a loan to replace the insulation ? \n"
    "Answer: yes\n"
    "\n"
    "Context information: As an employer, you can apply to the Central Arbitration Committee (CAC) to have a trade union derecognised if both of the following are true: \n you’ve employed less than 21 people for a continuous 13-week period \n "
    "Question: I am the owner of a high street retailing business which has fallen on hard times in the wake of the pandemic. At our peak we had over 150 employees, who were represented by a trade union whom we voluntarily recognised six years ago. Now our headcount has fallen below 20, and the remaining workers include a union shop steward who is being unreasonably obstructive of our attempts to turn the company around. I have had only 17 employees for the last year. Given the shrunken state of the business, is it now possible to get the union derecognised? \n"
    "Answer: yes\n"
    "\n"
    "Context information: You will not have access to your personal items in the test room. This includes things like: \n mobile phones \n You’ll usually have to store any personal items in a locker.\n If your test centre does not have lockers, you must:\n turn off your phone before you enter the test centre \n put your belongings in a clear plastic box that will be given to you - this must be stored under your desk during the test \n "
    "Question: My friend Ann has booked  her ADI part 1 test . She has scheduled an important phone call a few minutes before the exam day . Will she be allowed to access her mobile phone during exam day? \n"
    "Answer: no\n"
    "\n"
    "Context information: You could get £67.60 a week if you care for someone at least 35 hours a week and they get certain benefits.\n The person you care for must already get one of these benefits: \n Disability Living Allowance - the middle or highest care rate \n You need to spend at least 35 hours a week caring for someone. This can include: \n "
    "Question: I live in Scotland, and currently care for my physically disabled partner for approximately 30 hrs per week. My partner receives Disability Living Allowance at the higher rate and I work part time, earning approximately £500pcm. Can I claim Carer's Allowance to help with my partner's care? \n"
    "Answer: no\n"
    "\n"
    "---------------------\n"
    "Context information: {context_str}\n"
    "---------------------\n"
    "Question : {query_str}\n"
    "Output Format: Answer: __yes/no__ \n"
)

span_qa_c_s4_prompt = PromptTemplate(
    "You are a helpful assistant that answers questions given Context information and not prior knowledge.\n"
    "Answers must be a short span of the Context information. Do not write it depends or anything similar.\n" 
    "You have to extract the span from the Context information. Do not write anything else.\n"
    "Some examples are given below.\n"
    "---------------------\n"
    "Context information: Getting a decree nisi, If the judge agrees, the court will send you and your husband or wife a certificate. This may take several weeks., The certificate will tell you the time and date you’ll be granted a decree nisi., You’ll still be married after the decree nisi has been granted. You’ll have to wait 43 days (6 weeks and 1 day) before you can apply for a ‘decree absolute’ to actually end the marriage.\n "
    "Question: Me and my wife were married but with the mutual consent we applied for divorce. We have  applied for a decree nisi and are now waiting for the result What happens to my application and how I will be communicated with? \n"
    "Answer: if the judge agrees, the court will send you and your husband or wife a certificate. this may take several weeks.\n"
    "\n"
    "Context information: Apply by the standard route if all the following are true:, you’re 18 or over\n "
    "Question: I am a 16 year old living in Derby and was born male, I do not feel like I fit into any gender category. What age can I apply for a certificate? \n"
    "Answer: 18 or over\n"
    "\n"
    "Context information: Download and fill in a ‘notice of appeal’ form. You must include:\n "
    "Question: I am a 21 year old single Algerian male who is claiming asylum on the grounds of persecution. I applied for some support whilst I get myself established here but just received a letter saying I've been declined. What is the first step in the appeals process? \n"
    "Answer: download and fill in a ‘notice of appeal’ form\n"
    "\n"
    "Context information: You can ask your employer to set up an EWC if they have:, at least 1,000 employees in the EEA, 150 employees in each of at least 2 countries in the EEA\n"
    "Question: I work for a firm with several offices across Europe. I have heard of EWC but I am not sure if we qualify. Before I apply, what do we need to do to qualify? \n"
    "Answer: at least 1,000 employees in the eea\n"
    "\n"
    "---------------------\n"
    "Context information: {context_str}\n"
    "---------------------\n"
    "Question : {query_str}\n"
    "Output Format: Answer: __answer__ \n"
)

yes_no_con_qa_c_s4_prompt = PromptTemplate(
    "You are a helpful assistant that answers questions given Context information and not prior knowledge.\n"
    "Answers can be yes or no. You have to write yes or no and nothing else. Do not write it depends or anything similar.\n" 
    "You HAVE to write only yes or no, even if you are uncertain.\n"
    "Some answers may required the assumption of some sentences from the text to be true. If you think that is the case, you must write the full sentence(s) that you think are required to be true after the answer. We call these sentence(s) 'conditions'. You must have used this sentence(s) in your reasoning steps.\n"
    "Some examples are given below.\n"
    "---------------------\n"
    "Context information: If you owe Self Assessment tax and your bill is less than £30,000 you may be able to pay in monthly instalments. \n You can set up a payment plan online to spread the cost of your latest Self Assessment bill if: \n you owe £30,000 or less \n you do not have any other payment plans or debts with HMRC \n your tax returns are up to date \n it’s less than 60 days after the payment deadline \n If you pay a tax bill late you must pay interest on the amount you owe until it’s paid off. You can avoid penalties by arranging a payment plan with HMRC before the tax is due  – or by 1 April for Self Assessment.\n "
    "Question: I am self employed as a caterer and always do my own taxes. I was informed recently that I had made a mistake on my last self assessment form and owe quite a substantial amount of money to HMRC. I cannot pay at the present time. Is there anything I can do to delay the repayments I have to make? \n"
    "Answer: arranging a payment plan with hmrc Conditions: If you owe Self Assessment tax and your bill is less than £30,000 you may be able to pay in monthly instalments.\n you owe £30,000 or less \n you do not have any other payment plans or debts with HMRC \n your tax returns are up to date \n it’s less than 60 days after the payment deadline \n"
    "\n"
    "Context information: You may be eligible for help with your learning costs if you’re a full-time student with children. This is called Parents’ Learning Allowance. \n If you’re a student from England with dependent children you may qualify if you’re taking: \n a full-time undergraduate course \n an Initial Teacher Training (ITT) course \n "
    "Question: I have two children and I am currently due to start a degree course in social work this coming Autumn. Can I make a claim given that I will be studying and no longer working? \n"
    "Answer: yes Conditions: a full-time undergraduate course \n an Initial Teacher Training (ITT) course\n"
    "\n"
    "Context information: You’ll need a blank page in your passport for your visa if you’re: \n from outside the EU, Switzerland, Norway, Iceland or Liechtenstein \n from the EU, Switzerland, Norway, Iceland or Liechtenstein but do not have a biometric passport with a chip in it \n "
    "Question: I am 26 and planning on applying for a start-up visa for my new business in the UK. I speak fluent English. I have a valid passport but all the pages are full. Can I use my current passport for my application? \n"
    "Answer: no Conditions: from outside the EU, Switzerland, Norway, Iceland or Liechtenstein \n from the EU, Switzerland, Norway, Iceland or Liechtenstein but do not have a biometric passport with a chip in it\n"
    "\n"
    "Context information: If you sell your home within 10 years of buying it through Right to Buy, you must first offer it to either: \n your old landlord \n another social landlord in the area \n You can sell your home to anyone if the landlord does not agree to buy it within 8 weeks. \n Your former landlord may limit who you can sell your home to if your home is in: \n a national park \n an area of outstanding natural beauty \n an area the government says is rural for Right to Buy \n "
    "Question: I purchased my current family home in Norwich, England from the local council 9 years ago under the right-to-buy scheme. With my children having now grown up and left home my partner and I are now looking to sell the house and retire to something a little smaller. Can I now sell my home to whomever I like on the open market? \n"
    "Answer: no Conditions: a national park \n an area of outstanding natural beauty \n an area the government says is rural for Right to Buy\n"
    "\n"
    "---------------------\n"
    "Context information: {context_str}\n"
    "---------------------\n"
    "Question : {query_str}\n"
    "Output Format: Answer: __yes/no__ , Conditions: __condition__ \n __condition__ \n ..."
)

span_con_qa_c_s4_prompt = PromptTemplate(
    "You are a helpful assistant that answers questions given Context information and not prior knowledge.\n"
    "Answers must be a short span extracted from the Context information. Do not write it depends or anything similar.\n" 
    "You have to only extract the span of text from the Context information. Do not write anything else.\n"
    "Some answers may required the assumption of some sentences from the text to be true. If you think that is the case, you must write the full sentence(s) that you think are required to be true after the answer. We call these sentence(s) 'conditions'. You must have used this sentence(s) in your reasoning steps.\n"
    "Some examples are given below.\n"
    "---------------------\n"
    "Context information: ‘Offensive waste’ is non-clinical waste that’s non-infectious and does not contain pharmaceutical or chemical substances, but may be unpleasant to anyone who comes into contact with it.\n Healthcare offensive waste | Outer dressings and protective clothing like masks, gowns and gloves that are not contaminated with body fluids, and sterilised laboratory waste | Non-hazardous | 18-01-04 | 18-02-03 \n Infectious clinical waste (no chemicals or pharmaceuticals) - orange bag | Hazardous | 18-01-03* | 18-02-02* \n Infectious clinical waste - yellow bag | Hazardous | 18-01-03* and 18-01-06* | 18-02-02* and 18-02-05* \n "
    "Question: I am a GP partner in a small, private medical practice in London. We have recently gotten through a lot of gowns and other PPE as a result of the COVID-19 pandemic, and these now need to be classified for disposal. How are potentially COVID-infected gowns and other PPE to be classified? \n"
    "Answer: healthcare offensive waste Conditions: ‘Offensive waste’ is non-clinical waste that’s non-infectious and does not contain pharmaceutical or chemical substances, but may be unpleasant to anyone who comes into contact with it. \n Healthcare offensive waste | Outer dressings and protective clothing like masks, gowns and gloves that are not contaminated with body fluids, and sterilised laboratory waste | Non-hazardous | 18-01-04 | 18-02-03'\n'"
    "\n"
    "Context information: You can ask for permission to appeal to the Upper Tribunal (Immigration and Asylum Chamber) if you lose your case and you think there’s a legal mistake with the tribunal’s decision. \n For example, you think the tribunal: \n got the law wrong \n do not apply the correct law \n do not follow the correct procedures, which affected the decision  \n had no evidence to support its decision \n "
    "Question: I have recently had my appeal rejected and I am at a loss of what to do my family members are all in the uk and I wont be able to see them anymore. Is there anything I can do as my appeal has been rejected? \n"
    "Answer: you can ask for permission to appeal to the upper tribunal Conditions:  You can ask for permission to appeal to the Upper Tribunal (Immigration and Asylum Chamber) if you lose your case and you think there’s a legal mistake with the tribunal’s decision. \n got the law wrong \n do not apply the correct law \n do not follow the correct procedures, which affected the decision \n had no evidence to support its decision \n"
    "\n"
    "Context information: \n Maternity Allowance is usually paid to you if you do not qualify for Statutory Maternity Pay. \n You can claim Maternity Allowance as soon as you’ve been pregnant for 26 weeks. Payments can start 11 weeks before your baby is due.\n You could get either: \n £151.97 a week or 90% of your average weekly earnings (whichever is less) for 39 weeks \n £27 a week for 39 weeks \n You might get Maternity Allowance for 39 weeks if one of the following applies: \n you’re employed, but cannot get Statutory Maternity Pay \n In the 66 weeks before your baby’s due, you must also have been: \n employed or self-employed for at least 26 weeks \n earning (or classed as earning) £30 a week or more in at least 13 weeks - the weeks do not have to be together\n "
    "Question: I am twenty weeks pregnant and work part time at present.  I am not currently  in receipt of any other benefits. Am I eligible for the Maternity allowance and if so how much will I get? \n"
    "Answer: £151.97 a week or 90% of your average weekly earnings Conditions: \n you’re employed, but cannot get Statutory Maternity Pay \n employed or self-employed for at least 26 weeks  \n earning (or classed as earning) £30 a week or more in at least 13 weeks - the weeks do not have to be together\n"
    "\n"
    "Context information: You can request a Disclosure and Barring Service (DBS) check on behalf of an employee. \n If you provide care services for adults (for example in a care home), you can use a service called DBS Adult First.\n "
    "Question: I want to recruit an employee urgently to work in a care home.I want to know her DBS checks  in the next 2 days. Which service can i use? \n"
    "Answer: dbs adult first Conditions: If you provide care services for adults (for example in a care home), you can use a service called DBS Adult First.\n"
    "\n"
    "---------------------\n"
    "Context information: {context_str}\n"
    "---------------------\n"
    "Question : {query_str}\n"
    "Output Format: Answer: __answer__ , Conditions: __condition__ \n __condition__ \n ..."
)


############################################
# static few_shot Prompt  with Context + KG 4 examples   
############################################

yes_no_qa_ckg_s4_prompt = PromptTemplate(
    "You are a helpful assistant that answers questions given Context information and not prior knowledge.\n"
    "Answers can be yes or no. You have to write yes or no and nothing else. Do not write it depends or anything similar.\n"
    "The context may include knowledge triples in the format (subject, predicate, object). Use these triples as part of the Context information to help identify relevant information for answering the question.\n" 
    "You HAVE to write only yes or no, even if you are uncertain.\n"
    "Some examples are given below.\n"
    "---------------------\n"
    # "Context information: You can only get a finance plan for improvements recommended in your Green Deal assessment.\n"
    "Knowledge Triples: (finance plan, available for, Green Deal assessment improvements) \n (loan, available for, insulation replacement) \n "
    "Question: I own a home and energy bills are always high. When I hired a engineer to assess why my energy bills are high. He mentioned the problem is because of insulation. I can't afford to replace the insulation. These energy improvements have been recommended in my Green Deal assessment. Can I get a loan to replace the insulation ? \n"
    "Answer: yes\n"
    "\n"
    # "Context information: As an employer, you can apply to the Central Arbitration Committee (CAC) to have a trade union derecognised if both of the following are true: \n you’ve employed less than 21 people for a continuous 13-week period \n "
    "Knowledge Triples: (employer, applies to, Central Arbitration Committee) \n (trade union, derecognised if, employed less than 21 people for 13 weeks) \n"
    "Question: I am the owner of a high street retailing business which has fallen on hard times in the wake of the pandemic. At our peak we had over 150 employees, who were represented by a trade union whom we voluntarily recognised six years ago. Now our headcount has fallen below 20, and the remaining workers include a union shop steward who is being unreasonably obstructive of our attempts to turn the company around. I have had only 17 employees for the last year. Given the shrunken state of the business, is it now possible to get the union derecognised? \n"
    "Answer: yes\n"
    "\n"
    # "Context information: You will not have access to your personal items in the test room. This includes things like: \n mobile phones \n You’ll usually have to store any personal items in a locker.\n If your test centre does not have lockers, you must:\n turn off your phone before you enter the test centre \n put your belongings in a clear plastic box that will be given to you - this must be stored under your desk during the test \n "
    "Knowledge Triples: (test room, no access to, personal items) \n (mobile phones, stored in, locker or plastic box) \n"
    "Question: My friend Ann has booked  her ADI part 1 test . She has scheduled an important phone call a few minutes before the exam day . Will she be allowed to access her mobile phone during exam day? \n"
    "Answer: no\n"
     "\n"
    # "Context information: You could get £67.60 a week if you care for someone at least 35 hours a week and they get certain benefits.\n The person you care for must already get one of these benefits: \n Disability Living Allowance - the middle or highest care rate \n You need to spend at least 35 hours a week caring for someone. This can include: \n "
    "Knowledge Triples: (caregiver, receives, £67.60 a week) \n (caregiver, cares for, someone at least 35 hours a week) \n (Carer's Allowance, eligibility requires, 35 hours of care) \n (partner, receives, Disability Living Allowance at higher rate) \n"
    "Question: I live in Scotland, and currently care for my physically disabled partner for approximately 30 hrs per week. My partner receives Disability Living Allowance at the higher rate and I work part time, earning approximately £500pcm. Can I claim Carer's Allowance to help with my partner's care? \n"
    "Answer: no\n"
    # "\n"
    "---------------------\n"
    "Context information: {context_str}\n"
    "---------------------\n"
    "Question : {query_str}\n"
    "Output Format: Answer: __yes/no__ \n"
)

span_qa_ckg_s4_prompt = PromptTemplate(
    "You are a helpful assistant that answers questions given Context information and not prior knowledge.\n"
    "Answers must be a short span of the Context information. Do not write it depends or anything similar.\n" 
    "You have to extract the span from the Context information. Do not write anything else.\n"
    "The context may include knowledge triples in the format (subject, predicate, object). Use these triples as part of the Context information to help identify relevant information for answering the question.\n"
    "Some examples are given below.\n"
    "---------------------\n"
    # "Context information: Getting a decree nisi, If the judge agrees, the court will send you and your husband or wife a certificate. This may take several weeks., The certificate will tell you the time and date you’ll be granted a decree nisi., You’ll still be married after the decree nisi has been granted. You’ll have to wait 43 days (6 weeks and 1 day) before you can apply for a ‘decree absolute’ to actually end the marriage.\n "
    "Knowledge Triples: (judge, agrees, court sends certificate) \n (court, sends, certificate) \n (certificate, takes, several weeks) \n"
    "Question: Me and my wife were married but with the mutual consent we applied for divorce. We have  applied for a decree nisi and are now waiting for the result What happens to my application and how I will be communicated with? \n"
    "Answer: if the judge agrees, the court will send you and your husband or wife a certificate. this may take several weeks.\n"
    "\n"
    # "Context information: Apply by the standard route if all the following are true:, you’re 18 or over\n "
    "Knowledge Triples: (apply, requires, age 18 or over) \n"
    "Question: I am a 16 year old living in Derby and was born male, I do not feel like I fit into any gender category. What age can I apply for a certificate? \n"
    "Answer: 18 or over\n"
    "\n"
    # "Context information: Download and fill in a ‘notice of appeal’ form. You must include:\n "
    "Knowledge Triples: (first step, download and fill in, notice of appeal form) \n"
    "Question: I am a 21 year old single Algerian male who is claiming asylum on the grounds of persecution. I applied for some support whilst I get myself established here but just received a letter saying I've been declined. What is the first step in the appeals process? \n"
    "Answer: download and fill in a ‘notice of appeal’ form\n"
    "\n"
    # # "Context information: You can ask your employer to set up an EWC if they have:, at least 1,000 employees in the EEA, 150 employees in each of at least 2 countries in the EEA\n"
    "Knowledge Triples: (EWC, requires, at least 1,000 employees in EEA) \n (EWC, requires, 150 employees in each of at least 2 countries in EEA) \n"
    "Question: I work for a firm with several offices across Europe. I have heard of EWC but I am not sure if we qualify. Before I apply, what do we need to do to qualify? \n"
    "Answer: at least 1,000 employees in the eea\n"
    # "\n"
    "---------------------\n"
    "Context information: {context_str}\n"
    "---------------------\n"
    "Question : {query_str}\n"
    "Output Format: Answer: __answer__ \n"
)

yes_no_con_qa_ckg_s4_prompt = PromptTemplate(
    "You are a helpful assistant that answers questions given Context information and not prior knowledge.\n"
    "Answers can be yes or no. You have to write yes or no and nothing else. Do not write it depends or anything similar.\n" 
    "You HAVE to write only yes or no, even if you are uncertain.\n"
    "The context may include knowledge triples in the format (subject, predicate, object). Use these triples as part of the Context information to help identify relevant information for answering the question.\n"
    "Some answers may required the assumption of some sentences from the text to be true. If you think that is the case, you must write the full sentence(s) that you think are required to be true after the answer. We call these sentence(s) 'conditions'. You must have used this sentence(s) in your reasoning steps.\n"
    "Some examples are given below.\n"
    "---------------------\n"
    # "Context information: If you owe Self Assessment tax and your bill is less than £30,000 you may be able to pay in monthly instalments. \n You can set up a payment plan online to spread the cost of your latest Self Assessment bill if: \n you owe £30,000 or less \n you do not have any other payment plans or debts with HMRC \n your tax returns are up to date \n it’s less than 60 days after the payment deadline \n If you pay a tax bill late you must pay interest on the amount you owe until it’s paid off. You can avoid penalties by arranging a payment plan with HMRC before the tax is due  – or by 1 April for Self Assessment.\n "
    "Knowledge Triples: (arrange, payment plan, HMRC) \n (payment plan, requires, owe £30,000 or less) \n (payment plan, requires, no other payment plans or debts with HMRC) \n (payment plan, requires, tax returns up to date) \n (payment plan, requires, less than 60 days after payment deadline)\n"
    "Question: I am self employed as a caterer and always do my own taxes. I was informed recently that I had made a mistake on my last self assessment form and owe quite a substantial amount of money to HMRC. I cannot pay at the present time. Is there anything I can do to delay the repayments I have to make? \n"
    "Answer: arranging a payment plan with hmrc Conditions: If you owe Self Assessment tax and your bill is less than £30,000 you may be able to pay in monthly instalments.\n you owe £30,000 or less \n you do not have any other payment plans or debts with HMRC \n your tax returns are up to date \n it’s less than 60 days after the payment deadline \n"
    "\n"
    # # "Context information: You may be eligible for help with your learning costs if you’re a full-time student with children. This is called Parents’ Learning Allowance. \n If you’re a student from England with dependent children you may qualify if you’re taking: \n a full-time undergraduate course \n an Initial Teacher Training (ITT) course \n "
    "Knowledge Triples: (Parents’ Learning Allowance, available for, full-time student with children) \n (claim, available for, full-time undergraduate course) \n (claim, available for, Initial Teacher Training course)"
    "Question: I have two children and I am currently due to start a degree course in social work this coming Autumn. Can I make a claim given that I will be studying and no longer working? \n"
    "Answer: yes Conditions: a full-time undergraduate course \n an Initial Teacher Training (ITT) course\n"
    "\n"
    # "Context information: You’ll need a blank page in your passport for your visa if you’re: \n from outside the EU, Switzerland, Norway, Iceland or Liechtenstein \n from the EU, Switzerland, Norway, Iceland or Liechtenstein but do not have a biometric passport with a chip in it \n "
    "Knowledge Triples: (passport, requires, blank page for visa) \n (applicant, from, outside the EU/Switzerland/Norway/Iceland/Liechtenstein) \n (applicant, from, EU/Switzerland/Norway/Iceland/Liechtenstein without biometric passport) \n"
    "Question: I am 26 and planning on applying for a start-up visa for my new business in the UK. I speak fluent English. I have a valid passport but all the pages are full. Can I use my current passport for my application? \n"
    "Answer: no Conditions: from outside the EU, Switzerland, Norway, Iceland or Liechtenstein \n from the EU, Switzerland, Norway, Iceland or Liechtenstein but do not have a biometric passport with a chip in it\n"
    "\n"
    # "Context information: If you sell your home within 10 years of buying it through Right to Buy, you must first offer it to either: \n your old landlord \n another social landlord in the area \n You can sell your home to anyone if the landlord does not agree to buy it within 8 weeks. \n Your former landlord may limit who you can sell your home to if your home is in: \n a national park \n an area of outstanding natural beauty \n an area the government says is rural for Right to Buy \n "
    "Knowledge Triples: (home, must be offered to, old landlord or another social landlord) \n (sell, restricted in, national park) \n (sell, restricted in, area of outstanding natural beauty) \n (sell, restricted in, rural area for Right to Buy) \n"
    "Question: I purchased my current family home in Norwich, England from the local council 9 years ago under the right-to-buy scheme. With my children having now grown up and left home my partner and I are now looking to sell the house and retire to something a little smaller. Can I now sell my home to whomever I like on the open market? \n"
    "Answer: no Conditions: a national park \n an area of outstanding natural beauty \n an area the government says is rural for Right to Buy\n"
    "\n"
    "---------------------\n"
    "Context information: {context_str}\n"
    "---------------------\n"
    "Question : {query_str}\n"
    "Output Format: Answer: __yes/no__ , Conditions: __condition__ \n __condition__ \n ..."
)

span_con_qa_ckg_s4_prompt = PromptTemplate(
    "You are a helpful assistant that answers questions given Context information and not prior knowledge.\n"
    "Answers must be a short span extracted from the Context information. Do not write it depends or anything similar.\n" 
    "You have to only extract the span of text from the Context information. Do not write anything else.\n"
    "The context may include knowledge triples in the format (subject, predicate, object). Use these triples as part of the Context information to help identify relevant information for answering the question.\n"
    "Some answers may required the assumption of some sentences from the text to be true. If you think that is the case, you must write the full sentence(s) that you think are required to be true after the answer. We call these sentence(s) 'conditions'. You must have used this sentence(s) in your reasoning steps.\n"
    "Some examples are given below.\n"
    "---------------------\n"
    # "Context information: ‘Offensive waste’ is non-clinical waste that’s non-infectious and does not contain pharmaceutical or chemical substances, but may be unpleasant to anyone who comes into contact with it.\n Healthcare offensive waste | Outer dressings and protective clothing like masks, gowns and gloves that are not contaminated with body fluids, and sterilised laboratory waste | Non-hazardous | 18-01-04 | 18-02-03 \n Infectious clinical waste (no chemicals or pharmaceuticals) - orange bag | Hazardous | 18-01-03* | 18-02-02* \n Infectious clinical waste - yellow bag | Hazardous | 18-01-03* and 18-01-06* | 18-02-02* and 18-02-05* \n "
    "Knowledge Triples: (gowns and PPE, classified as, healthcare offensive waste) \n (offensive waste, defined as, non-clinical waste) \n (offensive waste, not contain, pharmaceutical or chemical substances) \n (offensive waste, may be unpleasant to, anyone who comes into contact) \n (healthcare offensive waste, includes, outer dressings and protective clothing like masks, gowns, gloves) \n (healthcare offensive waste, non-hazardous, 18-01-04 | 18-02-03) \n"
    "Question: I am a GP partner in a small, private medical practice in London. We have recently gotten through a lot of gowns and other PPE as a result of the COVID-19 pandemic, and these now need to be classified for disposal. How are potentially COVID-infected gowns and other PPE to be classified? \n"
    "Answer: healthcare offensive waste Conditions: ‘Offensive waste’ is non-clinical waste that’s non-infectious and does not contain pharmaceutical or chemical substances, but may be unpleasant to anyone who comes into contact with it. \n Healthcare offensive waste | Outer dressings and protective clothing like masks, gowns and gloves that are not contaminated with body fluids, and sterilised laboratory waste | Non-hazardous | 18-01-04 | 18-02-03'\n'"
    "\n"
    # # "Context information: You can ask for permission to appeal to the Upper Tribunal (Immigration and Asylum Chamber) if you lose your case and you think there’s a legal mistake with the tribunal’s decision. \n For example, you think the tribunal: \n got the law wrong \n do not apply the correct law \n do not follow the correct procedures, which affected the decision  \n had no evidence to support its decision \n "
    "Knowledge Triples: (ask for, permission to appeal to the Upper Tribunal) \n (appeal to Upper Tribunal, if, legal mistake with tribunal’s decision) \n (tribunal, got, law wrong) \n (tribunal, did not apply, correct law) \n (tribunal, did not follow, correct procedures) \n (tribunal, had no, evidence to support its decision) \n"
    "Question: I have recently had my appeal rejected and I am at a loss of what to do my family members are all in the uk and I wont be able to see them anymore. Is there anything I can do as my appeal has been rejected? \n"
    "Answer: you can ask for permission to appeal to the upper tribunal Conditions:  You can ask for permission to appeal to the Upper Tribunal (Immigration and Asylum Chamber) if you lose your case and you think there’s a legal mistake with the tribunal’s decision. \n got the law wrong \n do not apply the correct law \n do not follow the correct procedures, which affected the decision \n had no evidence to support its decision \n"
    "\n"
    # # "Context information: \n Maternity Allowance is usually paid to you if you do not qualify for Statutory Maternity Pay. \n You can claim Maternity Allowance as soon as you’ve been pregnant for 26 weeks. Payments can start 11 weeks before your baby is due.\n You could get either: \n £151.97 a week or 90% of your average weekly earnings (whichever is less) for 39 weeks \n £27 a week for 39 weeks \n You might get Maternity Allowance for 39 weeks if one of the following applies: \n you’re employed, but cannot get Statutory Maternity Pay \n In the 66 weeks before your baby’s due, you must also have been: \n employed or self-employed for at least 26 weeks \n earning (or classed as earning) £30 a week or more in at least 13 weeks - the weeks do not have to be together\n "
    "Knowledge Triples: (eligible for, Maternity Allowance) \n (Maternity Allowance, amount, £151.97 a week or 90% of average weekly earnings) \n (Maternity Allowance, paid if, cannot get Statutory Maternity Pay) \n (Maternity Allowance, requires, employed or self-employed for at least 26 weeks) \n (Maternity Allowance, requires, earning £30 a week or more in at least 13 weeks) \n "
    "Question: I am twenty weeks pregnant and work part time at present.  I am not currently  in receipt of any other benefits. Am I eligible for the Maternity allowance and if so how much will I get? \n"
    "Answer: £151.97 a week or 90% of your average weekly earnings Conditions: \n you’re employed, but cannot get Statutory Maternity Pay \n employed or self-employed for at least 26 weeks  \n earning (or classed as earning) £30 a week or more in at least 13 weeks - the weeks do not have to be together\n"
    "\n"
    # "Context information: You can request a Disclosure and Barring Service (DBS) check on behalf of an employee. \n If you provide care services for adults (for example in a care home), you can use a service called DBS Adult First.\n "
    "Knowledge Triples: (use, DBS Adult First) \n (DBS Adult First, available if, provide care services for adults) \n (care services, example, care home) \n"
    "Question: I want to recruit an employee urgently to work in a care home.I want to know her DBS checks  in the next 2 days. Which service can i use? \n"
    "Answer: dbs adult first Conditions: If you provide care services for adults (for example in a care home), you can use a service called DBS Adult First.\n"
    "\n"
    "---------------------\n"
    "Context information: {context_str}\n"
    "---------------------\n"
    "Question : {query_str}\n"
    "Output Format: Answer: __answer__ , Conditions: __condition__ \n __condition__ \n ..."
)


############################################
# static few_shot Prompt   6 examples   
############################################

yes_no_qa_s6_prompt = PromptTemplate(
        "You are a helpful assistant that answers questions given Context information and not prior knowledge.\n"
        "Answers can be yes or no. You have to write yes or no and nothing else. Do not write it depends or anything similar.\n" 
        "You HAVE to write only yes or no, even if you are uncertain.\n"
        "Some examples are given below.\n"
        "---------------------\n"
        # "{few_shot_examples}\n"
        "---------------------\n"
        "Context information: {context_str}\n"
        "---------------------\n"
        "Question : {query_str}\n"
        "Output Format: Answer: __yes/no__ \n"
    )

span_qa_s6_prompt = PromptTemplate(
        "You are a helpful assistant that answers questions given Context information and not prior knowledge.\n"
        "Answers must be a short span of the document. Do not write it depends or anything similar.\n" 
        "You have to extract the span from the document. Do not write anything else.\n"
        "Some examples are given below.\n"
        "---------------------\n"
        # "{few_shot_examples}\n"
        "---------------------\n"
        "Context information: {context_str}\n"
        "---------------------\n"
        "Question : {query_str}\n"
        "Output Format: Answer: __answer__ \n"
    )
    
yes_no_con_qa_s6_prompt = PromptTemplate(
        "You are a helpful assistant that answers questions given Context information and not prior knowledge.\n"
        "Answers can be yes or no. You have to write yes or no and nothing else. Do not write it depends or anything similar.\n" 
        "You HAVE to write only yes or no, even if you are uncertain.\n"
        "Some answers may required the assumption of some sentences from the text to be true. If you think that is the case, you must write the full sentence(s) that you think are required to be true after the answer. We call these sentence(s) 'conditions'. You must have used this sentence(s) in your reasoning steps.\n"
        "Some examples are given below.\n"
        "---------------------\n"
        # "{few_shot_examples}\n"
        "---------------------\n"
        "Context information: {context_str}\n"
        "---------------------\n"
        "Question : {query_str}\n"
        "Output Format: Answer: __yes/no__ , Conditions: __condition__ \n"
    )

span_con_qa_s6_prompt = PromptTemplate(
        "You are a helpful assistant that answers questions given Context information and not prior knowledge.\n"
        "Answers must be a short span extracted from the Context information. Do not write it depends or anything similar.\n" 
        "You have to only extract the span of text from the Context information. Do not write anything else.\n"
        "Some answers may required the assumption of some sentences from the text to be true. If you think that is the case, you must write the full sentence(s) that you think are required to be true after the answer. We call these sentence(s) 'conditions'. You must have used this sentence(s) in your reasoning steps.\n"
        "Some examples are given below.\n"
        "---------------------\n"
        # "{few_shot_examples}\n"
        "---------------------\n"
        "Context information: {context_str}\n"
        "---------------------\n"
        "Question : {query_str}\n"
        "Output Format: Answer: __answer__ , Conditions: __condition__ \n"
    )

############################################
# Dynamic few_shot Prompt
############################################


yes_no_qa_d_prompt = PromptTemplate(
        "You are a helpful assistant that answers questions given Context information and not prior knowledge.\n"
        # "The context may include knowledge triples in the format (subject, predicate, object). Use these triples as part of the Context information to help identify relevant information for answering the question.\n"
        "Answers can be yes or no. You have to write yes or no and nothing else. Do not write it depends or anything similar.\n"
        "Some examples are given below.\n"
        "---------------------\n"
        "{few_shot_examples}\n"
        "---------------------\n"
        "Context information: {context_str}\n"
        "---------------------\n"
        "Question : {query_str}\n"
        "Output Format: Answer: __yes/no__ \n"
    )

span_qa_d_prompt = PromptTemplate(
    "You are a helpful assistant that answers questions given Context information and not prior knowledge.\n"
    # "The context may include knowledge triples in the format (subject, predicate, object). Use these triples as part of the Context information to help identify relevant information for answering the question.\n"
    "Answers must be a short span of the Context information. Do not write it depends or anything similar.\n" 
    "You have to extract the span from the Context information. Do not write anything else.\n"
    "Some examples are given below.\n"
    "---------------------\n"
    "{few_shot_examples}\n"
    "---------------------\n"
    "Context information: {context_str}\n"
    "---------------------\n"
    "Question : {query_str}\n"
    "Output Format: Answer: __answer__ \n"
    )
    
yes_no_con_qa_d_prompt = PromptTemplate(
        "You are a helpful assistant that answers questions given Context information and not prior knowledge.\n"
        # "The context may include knowledge triples in the format (subject, predicate, object). Use these triples as part of the Context information to help identify relevant information for answering the question.\n"
        "Answers can be yes or no. You have to write yes or no and nothing else. Do not write it depends or anything similar.\n" 
        "You HAVE to write only yes or no, even if you are uncertain.\n"
        "Some answers may required the assumption of some sentences from the text to be true. If you think that is the case, you must write the full sentence(s) that you think are required to be true after the answer. We call these sentence(s) 'conditions'. You must have used this sentence(s) in your reasoning steps.\n"
        "Some examples are given below.\n"
        "---------------------\n"
        "{few_shot_examples}\n"
        "---------------------\n"
        "Context information: {context_str}\n"
        "---------------------\n"
        "Question : {query_str}\n"
        "Output Format: Answer: __yes/no__ , Conditions: __condition__ \n"
    )

span_con_qa_d_prompt = PromptTemplate(
        "You are a helpful assistant that answers questions given Context information and not prior knowledge.\n"
        # "The context may include knowledge triples in the format (subject, predicate, object). Use these triples as part of the Context information to help identify relevant information for answering the question.\n"
        "Answers must be a short span extracted from the Context information. Do not write it depends or anything similar.\n" 
        "You have to only extract the span of text from the Context information. Do not write anything else.\n"
        "Some answers may required the assumption of some sentences from the text to be true. If you think that is the case, you must write the full sentence(s) that you think are required to be true after the answer. We call these sentence(s) 'conditions'. You must have used this sentence(s) in your reasoning steps.\n"
        "Some examples are given below.\n"
        "---------------------\n"
        "{few_shot_examples}\n"
        "---------------------\n"
        "Context information: {context_str}\n"
        "---------------------\n"
        "Question : {query_str}\n"
        "Output Format: Answer: __answer__ , Conditions: __condition__ \n"
    )

############################################
# Knowledge-Graph Triplet Extraction Prompt
############################################

DEFAULT_KG_TRIPLET_EXTRACT_TMPL_1 = (
    "You are a Knowledge Graph creation expert. Some text is provided below. Given the text, extract all the relevant knowledge graph triplets in the form of (subject, predicate, object). Avoid stopwords. which will contain relevant information to answer questions . \n"
    "---------------------\n"
    "Example:\n"
    "Text: <p>Apply by the overseas route if your acquired gender has been legally accepted in an 'approved country or territory' and you have documents to prove it.</p>\n"
    "Triplets:\n(acquired gender, accepted in, approved country or territory)\n"
    "Text: <p>You must be 18 or over.</p>\n"
    "Triplets:\n(you, must be, 18 or over)\n"
    "Text: <tr>Overseas route | Form T453 | Leaflet T454</tr>\n"
    "Triplets:\n(apply, using, overseas route)\n"
    "Text: <p>If you’re applying using the overseas route, you must prove that your gender has been legally recognised in an 'approved country or territory'. Send original or certified copies of the following (if you have them):</p>\n"
    "Triplets:\n"
    "(gender, recognised in, approved country or territory)\n"
    "(send, copies of, documents)\n"
    "Text: <p>Apply by the standard route if all the following are true:</p>\n"
    "Triplets:\n(apply, by, standard route)\n"
    "Text: <li>you’re 18 or over</li>\n"
    "Triplets:\n(you, must be, 18 or over)\n"
    "Text: <p>You’ll get an 'interim certificate' if you or your spouse do not want to remain married, or if your spouse does not fill in a statutory declaration. You can use the interim certificate as grounds to end the marriage.</p>\n"
    "Triplets:\n"
    "(you, get, interim certificate)\n"
    "(spouse, fill in, statutory declaration)\n"
    "(use, interim certificate, end marriage)\n"
    "Text: <p>You and your spouse must fill in a statutory declaration saying you both agree to stay married.</p>\n"
    "Triplets:\n"
    "(you, spouse, fill in statutory declaration)\n"
    "(agree, stay, married)\n"
    "Text: <p>You can stay married if you apply for a Gender Recognition Certificate.</p>\n"
    "Triplets:\n(apply for, Gender Recognition Certificate, stay married)\n"
    "---------------------\n"
    "Text: {text}\n"
    "Triplets:\n"
)

DEFAULT_KG_TRIPLET_EXTRACT_TMPL_2 = (
    "Some text is provided below. Given the text, extract up to "
    "{max_knowledge_triplets} "
    "knowledge triplets in the form of (subject, predicate, object). Avoid stopwords.\n"
    "---------------------\n"
    "Example:\n"
    "Text: <p>Apply by the overseas route if your acquired gender has been legally accepted in an 'approved country or territory' and you have documents to prove it.</p>\n"
    "Triplets:\n(acquired gender, accepted in, approved country or territory)\n"
    "Text: <p>You must be 18 or over.</p>\n"
    "Triplets:\n(you, must be, 18 or over)\n"
    "Text: <tr>Overseas route | Form T453 | Leaflet T454</tr>\n"
    "Triplets:\n(apply, using, overseas route)\n"
    "Text: <p>If you’re applying using the overseas route, you must prove that your gender has been legally recognised in an 'approved country or territory'. Send original or certified copies of the following (if you have them):</p>\n"
    "Triplets:\n"
    "(gender, recognised in, approved country or territory)\n"
    "(send, copies of, documents)\n"
    "Text: <p>Apply by the standard route if all the following are true:</p>\n"
    "Triplets:\n(apply, by, standard route)\n"
    "Text: <li>you’re 18 or over</li>\n"
    "Triplets:\n(you, must be, 18 or over)\n"
    "Text: <p>You’ll get an 'interim certificate' if you or your spouse do not want to remain married, or if your spouse does not fill in a statutory declaration. You can use the interim certificate as grounds to end the marriage.</p>\n"
    "Triplets:\n"
    "(you, get, interim certificate)\n"
    "(spouse, fill in, statutory declaration)\n"
    "(use, interim certificate, end marriage)\n"
    "Text: <p>You and your spouse must fill in a statutory declaration saying you both agree to stay married.</p>\n"
    "Triplets:\n"
    "(you, spouse, fill in statutory declaration)\n"
    "(agree, stay, married)\n"
    "Text: <p>You can stay married if you apply for a Gender Recognition Certificate.</p>\n"
    "Triplets:\n(apply for, Gender Recognition Certificate, stay married)\n"
    "Text: {text}\n"
    "Triplets:\n"
)

DEFAULT_KG_TRIPLET_EXTRACT_TMPL_3 = (
    "System Prompt: You are a helpful assistant that answers questions using only the provided Context information, without relying on prior knowledge. Your task is to extract relevant knowledge graph triples from the text to support answering scenario-based questions. The output should form a well-connected, coherent, and comprehensive representation of the information, emphasizing relationships critical to the scenario. \n"
    "Contextual Relevance : Below is a text, followed by a scenario-based question and its answer. Extract knowledge triples in the form of (subject, predicate, object) from the text, prioritizing information directly relevant to answering the question. \n"
    "Form Connected Triples : When creating triples, establish connections across triples by reusing key terms where possible. Use the object of one triple as the subject in subsequent triples to enhance graph connectivity and continuity. \n"
    "Illustrate Relationships with Additional Triples : Build extra triples as necessary to effectively represent relationships within the text. Ensure that the graph captures implicit or complex connections between concepts, aiming for a cohesive and interconnected structure. \n"
    "Minimize Redundancy : Avoid stopwords and redundant terms in the triples. Focus on concise, meaningful terms to ensure clarity in each triple and throughout the graph. \n"
    "Maintain Coherence and Completeness : Strive to create a knowledge graph that is both thorough and logically organized. Capture key information and nuanced relationships, aiming for a comprehensive representation of the text that maximizes coherence. \n"
    "Some examples are given below.\n"
    "---------------------\n"
    "Text: <p>Apply by the overseas route if your acquired gender has been legally accepted in an 'approved country or territory' and you have documents to prove it.</p>\n"
    "Triplets:\n(acquired gender, accepted in, approved country or territory)\n"
    "Text: <p>You must be 18 or over.</p>\n"
    "Triplets:\n(you, must be, 18 or over)\n"
    "Text: <tr>Overseas route | Form T453 | Leaflet T454</tr>\n"
    "Triplets:\n(apply, using, overseas route)\n"
    "---------------------\n"
    "Text : {text}\n"
    "knowledge_triples :\n"
)

DEFAULT_KG_TRIPLET_EXTRACT_TMPL_4 = (
"You are an expert in Knowledge Graph (KG) construction. Your task is to extract relevant (subject, predicate, object) triplets from a text to create a well-structured and connected knowledge graph. Follow these steps systematically to ensure comprehensive and logically connected outputs:\n"
"1. Read and Understand\n"
"Carefully read the provided text. Identify the primary actions, facts, and key entities (e.g., people, objects, documents) involved. Focus on understanding the relationships between entities and actions critical to the context.\n"
"2. Identify Entities"
"Pinpoint the key subjects and objects in the text. These should be meaningful entities such as individuals, organizations, documents, or concepts. Avoid stopwords and redundant phrases, and focus on entities that are directly relevant to the given scenario.\n"
"3. Identify Relations"
"For each pair of entities, determine the relationship that connects them. These relations are often expressed as actions (verbs) or descriptors (e.g., 'requires', 'shows', 'supports'). Focus on capturing explicit and implied relationships."
"4. Replace Generic References (e.g., you)\n"
"If the text uses a generic reference like you, replace it with a more formal or specific term that reflects the context. Consider:\n"
"Formal options: Applicant, Individual, Person applying.\n"
"Context-specific options: Visa applicant, Job applicant\n"
"5. Formulate Triplets"
"Combine the identified entities and their relationships into clear (subject, predicate, object) triplets. Each triplet should encapsulate a meaningful piece of information.\n"
"6. Enhance Connectivity\n"
"Ensure the triplets are interconnected where possible. Use the object of one triplet as the subject of another if it logically extends the relationship. Add additional triplets if necessary to represent implicit connections.\n"
"7. Repeat for Completeness\n"
"Repeat this process to extract all relevant triplets from the text. Prioritize clarity, logical organization, and connectivity of the knowledge graph.\n"
"Example: Step-by-Step KG Construction\n"
"Text: \n"
"When you apply you’ll need to provide: your certificate of sponsorship reference number - your employer will give you this , a valid passport or other document that shows your identity and nationality , evidence that you have enough personal savings to support yourself in the UK, for example bank statements (unless your certificate of sponsorship shows your employer can support you) , proof of your relationship with your partner or children if they’re applying with you , your tuberculosis test results if you’re from a country where you have to take the test , a valid ATAS certificate if your employer tells you that you need one because your job involves researching a sensitive subject at PhD level or higher.\n"
"1. Read and Understand \n"
"This text lists requirements for applying, including documents and evidence needed. 'You' is addressed generically, so it will be replaced with 'applicant' or another suitable term.\n"
"2. Identify Entities\n"
"Subjects: applicant, certificate of sponsorship, passport, savings evidence, proof of relationship, tuberculosis test results, ATAS certificate. \n"
"Objects: reference number, identity and nationality, bank statements, partner or children, test results, PhD research. \n"
"3. Identify Relations \n"
"Relations include needs to provide, shows, supports, includes, and tells. \n"
"4. Replace You\n"
"Replace you with applicant for formal and specific reference. \n"
"5. Formulate Triplets \n"
"(applicant, needs to provide, certificate of sponsorship reference number)\n"
"(certificate of sponsorship, given by, employer)\n"
"(applicant, needs to provide, valid passport)\n"
"(valid passport, shows, identity and nationality)\n"
"(applicant, needs to provide, evidence of personal savings)\n"
"(evidence of personal savings, supports, applicant in the UK)\n"
"(applicant, needs to provide, proof of relationship)\n"
"(proof of relationship, includes, partner or children)\n"
"(applicant, needs to provide, tuberculosis test results)\n"
"(tuberculosis test results, required in, specific countries)\n"
"(applicant, needs to provide, valid ATAS certificate)\n"
"(employer, tells, applicant needs ATAS certificate)\n"
"(ATAS certificate, required for, PhD-level sensitive research)\n"
"6. Enhance Connectivity \n"
"Connect certificate of sponsorship to reference number through given by. \n"
"Connect evidence of personal savings to supports applicant in the UK. \n"
"Use employer as a linking entity for multiple relationships (e.g., ATAS certificate). \n"
"7. Final Knowledge Graph Triplets \n"
"(applicant, needs to provide, certificate of sponsorship reference number) \n"
"(certificate of sponsorship, given by, employer) \n"
"(applicant, needs to provide, valid passport) \n"
"(valid passport, shows, identity and nationality) \n"
"(applicant, needs to provide, evidence of personal savings) \n"
"(evidence of personal savings, supports, applicant in the UK) \n"
"(applicant, needs to provide, proof of relationship) \n"
"(proof of relationship, includes, partner or children) \n"
"(applicant, needs to provide, tuberculosis test results) \n"
"(tuberculosis test results, required in, specific countries) \n"
"(applicant, needs to provide, valid ATAS certificate) \n"
"(employer, tells, applicant needs ATAS certificate) \n"
"(ATAS certificate, required for, PhD-level sensitive research) \n"
"---------------------\n"
"Text : {text}\n"
"knowledge_triples :\n"
)



DEFAULT_KG_TRIPLET_EXTRACT_TMPL = (
    "Some text is provided below. Given the text, extract up to "
    "{max_knowledge_triplets} "
    "knowledge triplets in the form of (subject, predicate, object). Avoid stopwords.\n"
    "---------------------\n"
    "Example:"
    "Text: Alice is Bob's mother."
    "Triplets:\n(Alice, is mother of, Bob)\n"
    "Text: Philz is a coffee shop founded in Berkeley in 1982.\n"
    "Triplets:\n"
    "(Philz, is, coffee shop)\n"
    "(Philz, founded in, Berkeley)\n"
    "(Philz, founded in, 1982)\n"
    "---------------------\n"
    "Text: {text}\n"
    "Triplets:\n"
)

DEFAULT_KG_TRIPLET_EXTRACT_TMPL_2_LYNX = (
    "Some text is provided below. Given the text, extract up to {max_knowledge_triplets} knowledge graph triplets"
    "in the form of (subject, predicate, object) using the Lynx LKIF core ontology. "
    "Make sure to map the subjects and objects to the appropriate classes defined in the LKIF core ontology, "
    "and use relevant properties for the predicates. Focus on the following modules of the "
    "LKIF core ontology: legal action (e.g., LegalAction:PublicAct, LegalAction:LegalPerson, LegalAction:NaturalPerson), "
    "legal role (e.g., LegalRole:LegalProfession), and norm (e.g., Norm:LegalDocument, Norm:CustomaryLaw). "
    "Avoid using stopwords in the triplets. Ensure that the extracted triplets are consistent with the LKIF core ontology "
    "and accurately represent the legal information in the text."
    "Preserve the spaces between words in the sentence exactly as they appear. Do not remove or alter the spacing when generating or processing the text."
    "---------------------\n"
    "Example:\n"
    "Text: <p>Apply by the overseas route if your acquired gender has been legally accepted in an 'approved country or territory' and you have documents to prove it.</p>"
    "Triplets:\n(acquired gender, accepted in, approved country or territory) -> Maps to (LegalAction:AcquiredGender, Norm:AcceptedIn, Norm:ApprovedCountryOrTerritory)"
    "Text: <p>You must be 18 or over.</p>"
    "Triplets:\n(you, must be, 18 or over) -> Maps to (LegalRole:NaturalPerson, Norm:MustBe, Norm:AgeRequirement18OrOver)"
    "Text: <p>A company is a legal entity that is separate from its shareholders.</p>"
    "Triplets:\n"
    "(company, is, legal entity) -> Maps to (LegalAction:LegalPerson, Norm:Is, LegalAction:LegalEntity)"
    "(legal entity, separate from, shareholders) -> Maps to (LegalAction:LegalEntity, Norm:SeparateFrom, LegalRole:Shareholders)"
    "Text: <p>The judge ruled in favor of the defendant based on the constitutional rights.</p>"
    "Triplets:\n"
    "(judge, ruled in favor of, defendant) -> Maps to (LegalRole:LegalProfession, LegalAction:RuledInFavorOf, LegalRole:LegalPerson)"
    "(constitutional rights, are basis for, ruling) -> Maps to (Norm:ConstitutionalRights, Norm:AreBasisFor, LegalAction:Ruling)"
    "Text: {text}\n"
    "Triplets:\n"
)

MLT_PROMPT_1 = (
    "You are an expert in Knowledge Graph (KG) construction. Your task is to extract "
    "and construct a well-structured, comprehensive, and contextually accurate "
    "knowledge graph in the form of (subject, predicate, object) triplets from the provided text. "
    "Extract every relevant subject-predicate-object triple from the text in such a way that re-verbalizing these triples preserves all key information from the original text without any data loss."
    "Follow the systematic steps below to ensure thoroughness, logical connectivity, and context-specific accuracy:\n\n"
    "### Step 1: Analyze and Understand the Text ###\n"
    "1. Carefully read the provided text to understand its overall context, purpose, and primary actions.\n"
    "2. Determine the scope of the text, including:\n"
    "   - Specific conditions, rules, or exceptions.\n"
    "   - Procedural steps or alternative actions.\n"
    "3. Take note of any temporal, causal, or conditional relationships, including:\n"
    "   - Deadlines or sequences of events.\n"
    "   - Dependencies or consequences of actions.\n"
    "   - Edge cases or exceptions.\n\n"
    "Example for Context Understanding:\n"
    "Input Text: 'Applicants must submit the form within 30 days of receiving the decision.'\n"
    "Context Analysis: This text provides a procedural rule with a temporal condition "
    "('within 30 days') and an action ('submit the form').\n\n"
    "### Step 2: Extract Key Entities ###\n"
    "1. Identify meaningful entities, including subjects, objects, and key concepts, such as:\n"
    "   - Individuals: e.g., 'Applicant', 'Guardian'.\n"
    "   - Organizations: e.g., 'Court of Protection', 'HMRC'.\n"
    "   - Documents: e.g., 'Visa application', 'Grant proposal'.\n"
    "   - Concepts or actions: e.g., 'VAT exemption', 'Joint decision-making'.\n"
    "2. Exclude generic references (e.g., 'you', 'it') and replace them with specific terms reflecting context.\n"
    "   - Generic: 'You' → Contextual: 'Visa applicant'.\n"
    "   - Generic: 'It' → Contextual: 'The document', 'The application'.\n\n"
    "Example for Entity Extraction:\n"
    "Input Text: 'Applicants must submit the form within 30 days of receiving the decision.'\n"
    "Entities:\n"
    "- Subject: 'Applicant'\n"
    "- Predicate: 'submit'\n"
    "- Object: 'form'\n\n"
    "### Step 3: Extract Relationships ###\n"
    "1. Identify relationships connecting the extracted entities. Focus on:\n"
    "   - Explicit actions: e.g., 'requires', 'prohibits', 'allows'.\n"
    "   - Procedural links: e.g., 'must be approved by', 'needs to be filed with'.\n"
    "   - Conditional relations: e.g., 'if consent is not obtained, seek court approval'.\n"
    "2. Capture implied relationships, such as:\n"
    "   - Temporal dependencies: e.g., 'must be submitted within 12 months'.\n"
    "   - Causal or procedural links: e.g., 'failure to comply leads to rejection'.\n\n"
    "Example for Relationship Extraction:\n"
    "Input Text: 'Applicants must submit the form within 30 days of receiving the decision.'\n"
    "Relationships:\n"
    "- ('Applicant', 'must submit', 'form')\n"
    "- ('form', 'must be submitted within', '30 days')\n"
    "- ('30 days', 'depends on', 'receiving the decision')\n\n"
    "------------------------\n"
    "{text}\n"
    "------------------------\n"
    "### Output Format ###\n"
    "Context Analysis:\n"
    "- Summary of the context and purpose of the text\n\n"
    "Entities:\n"
    "- List of extracted entities\n\n"
    "Relationships:\n"
    "- (Entity 1, Predicate, Entity 2)\n"
    "- (Entity 3, Predicate, Entity 4)\n"
)



MLT_PROMPT_2 = (
    "You are an expert in Knowledge Graph (KG) construction. Your task is to use the output of a previous analysis "
    "and additional unstructured text to extract conditional and alternative scenarios, and to formulate initial knowledge graph triplets. "
    "Extract every relevant subject-predicate-object triple from the text in such a way that re-verbalizing these triples preserves all key information from the original text without any data loss."
    "Ensure that the output is logically connected and contextually accurate.\n\n"

    "### Inputs Provided ###\n"
    "1. **Extracted Entities and Relationships:**\n"
    "{intermediate_extracted}\n\n"
    "2. **Unstructured Text:**\n"
    "{text}\n\n"

    "### Instructions ###\n"
    "Follow these steps to complete the task:\n\n"

    "### Step 4: Address Conditional and Alternative Scenarios ###\n"
    "1. Identify all conditional or alternative pathways explicitly or implicitly stated in the text:\n"
    "   - For example: 'If consent is not given, then permission must be obtained from the court.'\n"
    "   - For example: 'Zero-rated sales are excluded from VAT registration threshold calculations.'\n"
    "2. Capture nuances of exceptions, alternative actions, or scenarios where specific conditions apply.\n\n"

    "### Step 5: Formulate Initial Triplets ###\n"
    "1. Combine the extracted entities and relationships with the identified conditional and alternative scenarios.\n"
    "2. Formulate clear (subject, predicate, object) triplets that capture:\n"
    "   - Meaningful actions and rules.\n"
    "   - Conditions and their consequences.\n"
    "   - Alternative pathways or exceptions.\n"
    "3. Ensure each triplet is distinct and logically connected.\n"
    "4. Avoid redundant or vague triplets.\n\n"

    "### Output Format ###\n"
    "Conditional and Alternative Scenarios:\n"
    "- Condition 1: If X, then Y\n"
    "- Condition 2: Alternative action A if action B is not possible\n\n"

    "Initial Triplets:\n"
    "- (Subject 1, Predicate, Object)\n"
    "- (Subject 2, Predicate, Object)\n"
    "- (Subject 3, Predicate, Object)\n"
)

MLT_PROMPT_3 = (
    "You are an expert in Knowledge Graph (KG) construction. Your task is to refine the provided triplets by enhancing "
    "logical connectivity and validating completeness and specificity. Use the output of the previous analysis and the original text "
    "Extract every relevant subject-predicate-object triple from the text in such a way that re-verbalizing these triples preserves all key information from the original text without any data loss."
    "to ensure the knowledge graph is thorough, accurate, and logically connected.\n\n"

    "### Inputs Provided ###\n"
    "1. **Initial Triplets:**\n"
    "{intermediate_extracted}\n\n"
    "2. **Unstructured Text:**\n"
    "{text}\n\n"

    "### Instructions ###\n"
    "Follow these steps systematically to refine and enhance the knowledge graph:\n\n"

    "### Step 6: Enhance Logical Connectivity ###\n"
    "1. Interconnect triplets to reflect complex relationships:\n"
    "   - Use the object of one triplet as the subject of another if logically connected.\n"
    "   - For example:\n"
    "     - ('Guardian', 'needs consent from', 'Parents').\n"
    "     - ('Parents', 'can delegate consent to', 'Court of Protection').\n"
    "     - Derived Triplet: ('Guardian', 'can delegate consent to', 'Court of Protection').\n"
    "2. Add new triplets to represent implicit relationships or logical extensions:\n"
    "   - For example:\n"
    "     - If ('A', 'requires', 'B') and ('B', 'enables', 'C'), create ('A', 'enables', 'C').\n\n"

    "### Step 7: Validate Completeness and Specificity ###\n"
    "1. Review the triplets to ensure they cover all explicit and implicit details from the text.\n"
    "2. Validate that the triplets address:\n"
    "   - Procedural or conditional scenarios.\n"
    "   - Exceptions or edge cases.\n"
    "3. Ensure that all relationships are specific and unambiguous:\n"
    "   - Avoid generic or vague relationships (e.g., 'Gift', 'has duty', 'Customs').\n"
    "   - Prefer specific relationships (e.g., 'Gift under £100', 'is exempt from', 'Customs duty').\n\n"

    "### Output Format ###\n"
    "Return only the final triplets in the strict format (subject, predicate, object), one triplet per line. "
    "Ensure the triplets are free of extraneous text, redundant characters, or missing components.\n\n"

    "Enhanced Triplets:\n"
    "(Subject 1, Predicate, Object)\n"
    "(Subject 2, Predicate, Object)\n"
    "(Subject 3, Predicate, Object)\n"
)